name: EconRepair
description: A Bukkit plugin for detailed repair costs
author: IAMVISHNU Media
website: iamvishnu.net
api-version: 1.16
version: 0.0.1
main: net.iamvishnu.EconRepair.EconRepair
depend: [Vault]

commands:
    econrepair:
        description: See help info or reload config
        useage: /econrepair (help | reload)
        aliases: [ecr, er]
    repair:
        description: Repairs user's items for a cost
        useage: /repair (all)
        aliases: rpr
        permission: econrepair.repair
permissions:
    econrepair.repair:
        description: Allows users to repair items in hand
        default: false
    econrepair.repair.all:
        description: Allows users to repair all items in inventory
        default: false
        children:
            econrepair.repair: true
    econrepair.reload:
        description: Allows users to reload the plugin's configuration.
        default: op